create table transactions (amount float(53) not null, id integer not null, receiver_id integer not null, sender_id integer not null, description varchar(255), primary key (id)) engine=InnoDB;
create table transactions_seq (next_val bigint) engine=InnoDB;
insert into transactions_seq values ( 1 );
create table user_connections (connection_id integer not null, user_id integer not null) engine=InnoDB;
create table users (balance float(53) not null, id integer not null, email varchar(255), password varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table transactions add constraint FK5nn8ird7idyxyxki68gox2wbx foreign key (receiver_id) references users (id);
alter table transactions add constraint FK3ly4r8r6ubt0blftudix2httv foreign key (sender_id) references users (id);
alter table user_connections add constraint FKohvj3bhf0c6gb645k4atn4rax foreign key (connection_id) references users (id);
alter table user_connections add constraint FK56b5yg0vwv72mhph7e5u2hn6x foreign key (user_id) references users (id);
create table transactions (amount float(53) not null, id integer not null, receiver_id integer not null, sender_id integer not null, description varchar(255), primary key (id)) engine=InnoDB;
create table transactions_seq (next_val bigint) engine=InnoDB;
insert into transactions_seq values ( 1 );
create table user_connections (connection_id integer not null, user_id integer not null) engine=InnoDB;
create table users (balance float(53) not null, id integer not null, email varchar(255), password varchar(255), username varchar(255), primary key (id)) engine=InnoDB;
create table users_seq (next_val bigint) engine=InnoDB;
insert into users_seq values ( 1 );
alter table users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table users add constraint UKr43af9ap4edm43mmtq01oddj6 unique (username);
alter table transactions add constraint FK5nn8ird7idyxyxki68gox2wbx foreign key (receiver_id) references users (id);
alter table transactions add constraint FK3ly4r8r6ubt0blftudix2httv foreign key (sender_id) references users (id);
alter table user_connections add constraint FKohvj3bhf0c6gb645k4atn4rax foreign key (connection_id) references users (id);
alter table user_connections add constraint FK56b5yg0vwv72mhph7e5u2hn6x foreign key (user_id) references users (id);